
raffle_web_homepage:
    path: /
    defaults: { _controller: 'App\Controller\RaffleWebController::index' }

raffle_web_start:
    path: /raffle/start
    methods: [POST]
    defaults: { _controller: 'App\Controller\RaffleWebController::start' }

raffle_web_show:
    path: /raffle/{id}
    defaults: { _controller: 'App\Controller\RaffleWebController::show' }

raffle_web_pick:
    path: /raffle/{id}/pick
    methods: [POST]
    defaults: { _controller: 'App\Controller\RaffleWebController::pick' }

raffle_web_winner:
    path: /raffle/{id}/winner/{userId}
    methods: [POST]
    defaults: { _controller: 'App\Controller\RaffleWebController::winner' }

raffle_web_noshow:
    path: /raffle/{id}/no_show/{userId}
    methods: [POST]
    defaults: { _controller: 'App\Controller\RaffleWebController::noShow' }